// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/19/2025, 7:22:11 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/mdmuhir/Desktop/Jay-Website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/mdmuhir/Desktop/Jay-Website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/mdmuhir/Desktop/Jay-Website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/mdmuhir/Desktop/Jay-Website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/mdmuhir/Desktop/Jay-Website/plugins/**/*.{js,ts,mjs}","/home/mdmuhir/Desktop/Jay-Website/composables/**/*.{js,ts,mjs}","/home/mdmuhir/Desktop/Jay-Website/utils/**/*.{js,ts,mjs}","/home/mdmuhir/Desktop/Jay-Website/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/mdmuhir/Desktop/Jay-Website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/mdmuhir/Desktop/Jay-Website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/mdmuhir/Desktop/Jay-Website/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;