// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/23/2025, 9:32:14 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/MD MUHIR/Desktop/content_creator-s_portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MD MUHIR/Desktop/content_creator-s_portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MD MUHIR/Desktop/content_creator-s_portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MD MUHIR/Desktop/content_creator-s_portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MD MUHIR/Desktop/content_creator-s_portfolio/plugins/**/*.{js,ts,mjs}","C:/Users/MD MUHIR/Desktop/content_creator-s_portfolio/composables/**/*.{js,ts,mjs}","C:/Users/MD MUHIR/Desktop/content_creator-s_portfolio/utils/**/*.{js,ts,mjs}","C:/Users/MD MUHIR/Desktop/content_creator-s_portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MD MUHIR/Desktop/content_creator-s_portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MD MUHIR/Desktop/content_creator-s_portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/MD MUHIR/Desktop/content_creator-s_portfolio/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;